/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otogaleriproje;

import java.awt.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicListUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mert
 */
public class MusteriEkrani extends javax.swing.JFrame {

     DefaultTableModel model,model2;
    Clock clock = new Clock();
    VeritabaniIslemleri islemler = new VeritabaniIslemleri();
    
    public void click()
    {
      tblArac.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblArac.rowAtPoint(evt.getPoint());
        
        String seciliKS = model.getValueAt(row, 5).toString();
        if (seciliKS.equals("Satıldı") ) {
            btnSatinAl.setEnabled(false);
        }
        else
        {
         btnSatinAl.setEnabled(true);
        }
        if (seciliKS.equals("Kiralandı")) {
            btnKirala.setEnabled(false);
        }
        else
        {
         btnKirala.setEnabled(true);
        }
    }
});
    
    }
    
           public void aracGoruntule()
    {
        model.setRowCount(0);
        ArrayList<AracBilgi> araclar = new ArrayList<AracBilgi>();
        araclar = islemler.aracListele();
        
        if (araclar!=null) {
            for(AracBilgi item : araclar)
            {
             Object[] eklenecek = {item.getArac_Plaka(),item.getArac_Marka(),item.getArac_Model(),item.getArac_Tipi(),item.getArac_YakitTip(),item.getArac_KiraSat(),item.getArac_Fiyat(),item.getArac_MotorHacmi()};
             model.addRow(eklenecek);
            }
        }
        
    }
           
       public void aracGoruntule2(String marka,String aracTip,String yakitTip,String alimTip,String minMotorHacmi,String maxMotorHacmi,String minFiyat,String maxFiyat)
    {
        model.setRowCount(0);
        
        ArrayList<AracBilgi> araclar = new ArrayList<AracBilgi>();
        araclar = islemler.aracFiltrele(marka,aracTip,yakitTip,alimTip,minMotorHacmi,maxMotorHacmi,minFiyat,maxFiyat);
        
        if (araclar!=null) {
            for(AracBilgi item : araclar)
            {
             Object[] eklenecek = {item.getArac_Plaka(),item.getArac_Marka(),item.getArac_Model(),item.getArac_Tipi(),item.getArac_YakitTip(),item.getArac_KiraSat(),item.getArac_Fiyat(),item.getArac_MotorHacmi()};
             model.addRow(eklenecek);
            }
        }
        
    }
             
             
                public void personelLabel(int id)
    {
        
        
        ArrayList<PersonelBilgi> araclar = new ArrayList<PersonelBilgi>();
        araclar = islemler.personelListele(id);
        
        if (araclar!=null) {
            for(PersonelBilgi item : araclar)
            {
             
             lblPersonel.setText("İlgili Personeliniz : " +item.getPersonel_Adi());
            }
        }
        
    }
    
    
        
    
    
    
    
    public MusteriEkrani() {
        initComponents();
        model = (DefaultTableModel)tblArac.getModel();
        clock.Clock(lblClock);
        
        click();
        personelLabel(0);
        aracGoruntule();
        lblUyari.setVisible(false);
         
        tblArac.setAutoCreateRowSorter(true);
    }
    
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAlim = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbAracTipi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbYakit = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbMarka = new javax.swing.JComboBox<>();
        btnFiltreTemizle = new javax.swing.JButton();
        btnFiltrele = new javax.swing.JButton();
        btnKirala = new javax.swing.JButton();
        btnSatinAl = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArac = new javax.swing.JTable();
        btnIslemDegistir = new javax.swing.JButton();
        tbMotorAz = new javax.swing.JTextField();
        tbMotorCok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbFiyatAz = new javax.swing.JTextField();
        tbFiyatCok = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblUyari = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblPersonel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cmbAlim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S(Satılık)", "K(Kiralık)" }));
        getContentPane().add(cmbAlim);
        cmbAlim.setBounds(56, 66, 147, 20);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Alım Tipi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 34, 38, 14);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Araç Tipi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(56, 104, 41, 14);

        cmbAracTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Hatchback" }));
        cmbAracTipi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAracTipiİtemStateChanged(evt);
            }
        });
        getContentPane().add(cmbAracTipi);
        cmbAracTipi.setBounds(56, 136, 147, 20);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Motor Hacmi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(56, 174, 59, 14);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Fiyat Aralığı");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 269, 56, 14);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Yakıt Tipi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(56, 382, 42, 14);

        cmbYakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benzin", "Dizel", "LPG", "Hibrit" }));
        getContentPane().add(cmbYakit);
        cmbYakit.setBounds(56, 402, 137, 20);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Marka");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(56, 433, 29, 14);

        cmbMarka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiat", "Hyundai", "Ford", "Audi", "BMW", "Jaguar", "Dodge", "Opel", "McLaren", "Mercedes", "Maserati", "Honda", "Lamborghini", "Tofaş", "Ferrari", "Peugeot" }));
        cmbMarka.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMarkaİtemStateChanged(evt);
            }
        });
        getContentPane().add(cmbMarka);
        cmbMarka.setBounds(56, 465, 137, 20);

        btnFiltreTemizle.setText("Filtreleri Temizle");
        btnFiltreTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltreTemizleActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltreTemizle);
        btnFiltreTemizle.setBounds(56, 579, 137, 45);

        btnFiltrele.setText("Filtrele");
        btnFiltrele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltreleActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrele);
        btnFiltrele.setBounds(56, 503, 137, 45);

        btnKirala.setText("Araç Kirala");
        btnKirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiralaActionPerformed(evt);
            }
        });
        getContentPane().add(btnKirala);
        btnKirala.setBounds(754, 522, 126, 58);

        btnSatinAl.setText("Araç Satın Al");
        btnSatinAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatinAlActionPerformed(evt);
            }
        });
        getContentPane().add(btnSatinAl);
        btnSatinAl.setBounds(587, 522, 132, 58);

        tblArac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plaka", "Marka", "Model", "Araç Tipi", "Yakıt Tipi", "Kiralık/Satılık", "Fiyat", "Motor Hacmi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArac.getTableHeader().setReorderingAllowed(false);
        tblArac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAracMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblArac);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(222, 34, 851, 458);

        btnIslemDegistir.setText("İşlem Değiştir");
        btnIslemDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIslemDegistirActionPerformed(evt);
            }
        });
        getContentPane().add(btnIslemDegistir);
        btnIslemDegistir.setBounds(433, 522, 119, 58);
        getContentPane().add(tbMotorAz);
        tbMotorAz.setBounds(56, 194, 147, 20);
        getContentPane().add(tbMotorCok);
        tbMotorCok.setBounds(56, 225, 147, 20);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("En Az :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 197, 40, 14);

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("En Çok :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 228, 40, 14);
        getContentPane().add(tbFiyatAz);
        tbFiyatAz.setBounds(56, 294, 147, 20);
        getContentPane().add(tbFiyatCok);
        tbFiyatCok.setBounds(56, 344, 147, 20);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("En Az :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 297, 40, 14);

        lblUyari.setForeground(new java.awt.Color(240, 240, 240));
        lblUyari.setText("Yeni bir Filtreleme İçin Filtreleri Temizleyin");
        getContentPane().add(lblUyari);
        lblUyari.setBounds(25, 554, 197, 14);

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("En Çok :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 347, 40, 14);

        lblClock.setForeground(new java.awt.Color(51, 0, 51));
        lblClock.setText("jLabel2");
        getContentPane().add(lblClock);
        lblClock.setBounds(1023, 586, 34, 14);

        lblPersonel.setForeground(new java.awt.Color(51, 0, 51));
        lblPersonel.setText("jLabel9");
        getContentPane().add(lblPersonel);
        lblPersonel.setBounds(352, 610, 34, 14);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otogaleriproje/JAVA ARKA PLAN-2.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(630, 0, 500, 660);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otogaleriproje/JAVA ARKA PLAN-2.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-20, 0, 490, 660);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otogaleriproje/JAVA ARKA PLAN-2.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(460, 0, 500, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMarkaİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMarkaİtemStateChanged
      
       
    }//GEN-LAST:event_cmbMarkaİtemStateChanged

    private void cmbAracTipiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAracTipiİtemStateChanged
       
    }//GEN-LAST:event_cmbAracTipiİtemStateChanged

    private void btnFiltreTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreTemizleActionPerformed
        cmbAlim.setSelectedIndex(0);
        cmbAracTipi.setSelectedIndex(0);
        cmbMarka.setSelectedIndex(0);
        tbFiyatAz.setText("");
        tbFiyatCok.setText("");
        tbMotorAz.setText("");
        tbMotorCok.setText("");
        cmbYakit.setSelectedIndex(0);
        model = (DefaultTableModel)tblArac.getModel();
        aracGoruntule();
        btnFiltrele.setEnabled(true);
        
    }//GEN-LAST:event_btnFiltreTemizleActionPerformed

    private void btnFiltreleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreleActionPerformed
        
        String marka = cmbMarka.getSelectedItem().toString();
        String aracTip = cmbAracTipi.getSelectedItem().toString();
        String yakitTip = cmbYakit.getSelectedItem().toString();
        String alimTip = "";
        String minFiyat = tbFiyatAz.getText();
        String maxFiyat = tbFiyatCok.getText();
        String minMotorHacmi = tbMotorAz.getText();
        String maxMotorHacmi = tbMotorCok.getText();
        int rowcount =tblArac.getRowCount();
        if (rowcount==0) {

                JOptionPane.showMessageDialog(this, "Filtrelediğiniz Biçimde Araç Bulunmamaktadır");
            }
            
        if (cmbAlim.getSelectedItem().toString()=="S(Satılık)") {
        alimTip = "S";
        }
        else
        {
         alimTip = "K";
        }
        
        if (tbFiyatAz.getText().isEmpty() || tbFiyatCok.getText().isEmpty()|| tbMotorAz.getText().isEmpty() || tbMotorCok.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alanlar Boş Bırakılamaz. Lütfen yeni bir filtre seçin");
   
        }
        else
        {
               
    aracGoruntule2(marka,aracTip,yakitTip,alimTip,minMotorHacmi,maxMotorHacmi,minFiyat,maxFiyat);
    
        

            

        
        
    btnFiltrele.setEnabled(false);
    lblUyari.setVisible(true);
        }
        
       
       

        
        
 
    
        
    }//GEN-LAST:event_btnFiltreleActionPerformed

    private void btnIslemDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIslemDegistirActionPerformed
        IslemEkrani islem = new IslemEkrani();
        this.setVisible(false);
        islem.setVisible(true);
    }//GEN-LAST:event_btnIslemDegistirActionPerformed

    private void btnSatinAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatinAlActionPerformed
        
        KasaEkrani ekran = new KasaEkrani();
      ekran.setVisible(true);
        
      
    }//GEN-LAST:event_btnSatinAlActionPerformed

    private void btnKiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiralaActionPerformed
       
      KasaEkrani ekran = new KasaEkrani();
      ekran.setVisible(true);
        
        
    }//GEN-LAST:event_btnKiralaActionPerformed

    private void tblAracMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAracMouseClicked
      
    }//GEN-LAST:event_tblAracMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltreTemizle;
    private javax.swing.JButton btnFiltrele;
    private javax.swing.JButton btnIslemDegistir;
    private javax.swing.JButton btnKirala;
    private javax.swing.JButton btnSatinAl;
    private javax.swing.JComboBox<String> cmbAlim;
    private javax.swing.JComboBox<String> cmbAracTipi;
    private javax.swing.JComboBox<String> cmbMarka;
    private javax.swing.JComboBox<String> cmbYakit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClock;
    public static javax.swing.JLabel lblPersonel;
    private javax.swing.JLabel lblUyari;
    private javax.swing.JTextField tbFiyatAz;
    private javax.swing.JTextField tbFiyatCok;
    private javax.swing.JTextField tbMotorAz;
    private javax.swing.JTextField tbMotorCok;
    public static javax.swing.JTable tblArac;
    // End of variables declaration//GEN-END:variables
}
