/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otogaleriproje;

/**
 *
 * @author Mert
 */
public class SatmaEkrani extends javax.swing.JFrame {

    VeritabaniIslemleri islem = new VeritabaniIslemleri();
    Clock clock = new Clock();
    
    public SatmaEkrani() {
        initComponents();
        clock.Clock(lblClock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgirlik = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbPlaka = new javax.swing.JTextField();
        tbAracFiyati = new javax.swing.JTextField();
        tbMarka = new javax.swing.JTextField();
        tbModel = new javax.swing.JTextField();
        lblPlaka = new javax.swing.JLabel();
        btnAracSat = new javax.swing.JButton();
        tbMotorHacmi = new javax.swing.JTextField();
        tbAracTipi = new javax.swing.JTextField();
        lblSaat1 = new javax.swing.JLabel();
        lblPlaka1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbYakitTipi = new javax.swing.JTextField();
        lblClock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblAgirlik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAgirlik.setForeground(new java.awt.Color(240, 240, 240));
        lblAgirlik.setText("Araç Markası: ");
        getContentPane().add(lblAgirlik);
        lblAgirlik.setBounds(30, 90, 111, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Araç Bilgileri :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 10, 108, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Araç Fiyatı :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 200, 93, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Araç Plakası :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 240, 105, 22);
        getContentPane().add(tbPlaka);
        tbPlaka.setBounds(160, 250, 143, 20);
        getContentPane().add(tbAracFiyati);
        tbAracFiyati.setBounds(160, 210, 143, 20);
        getContentPane().add(tbMarka);
        tbMarka.setBounds(160, 90, 143, 20);
        getContentPane().add(tbModel);
        tbModel.setBounds(160, 50, 143, 20);

        lblPlaka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlaka.setForeground(new java.awt.Color(240, 240, 240));
        lblPlaka.setText("Araç Modeli:");
        getContentPane().add(lblPlaka);
        lblPlaka.setBounds(30, 50, 110, 22);

        btnAracSat.setText("Araç Sat");
        btnAracSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAracSatActionPerformed(evt);
            }
        });
        getContentPane().add(btnAracSat);
        btnAracSat.setBounds(160, 330, 132, 50);
        getContentPane().add(tbMotorHacmi);
        tbMotorHacmi.setBounds(160, 120, 143, 20);
        getContentPane().add(tbAracTipi);
        tbAracTipi.setBounds(160, 160, 143, 20);

        lblSaat1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaat1.setForeground(new java.awt.Color(240, 240, 240));
        lblSaat1.setText("Motor Hacmi :");
        getContentPane().add(lblSaat1);
        lblSaat1.setBounds(30, 120, 112, 22);

        lblPlaka1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlaka1.setForeground(new java.awt.Color(240, 240, 240));
        lblPlaka1.setText("Araç Tipi :");
        getContentPane().add(lblPlaka1);
        lblPlaka1.setBounds(30, 160, 81, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Yakıt Tipi :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 290, 85, 22);
        getContentPane().add(tbYakitTipi);
        tbYakitTipi.setBounds(160, 290, 143, 20);

        lblClock.setText("jLabel8");
        getContentPane().add(lblClock);
        lblClock.setBounds(430, 540, 34, 14);

        jButton1.setText("İşlem Değiştir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 400, 132, 58);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otogaleriproje/JAVA ARKA PLAN-2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 500, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAracSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAracSatActionPerformed
       
        String marka = tbMarka.getText();
        String model = tbModel.getText();
        String aracTipi = tbAracTipi.getText();
        int fiyat = Integer.parseInt(tbAracFiyati.getText());
        String yakitTipi = tbYakitTipi.getText();
        String plaka = tbPlaka.getText();
        String motorHacmi = tbMotorHacmi.getText();
        int satildiMi = 0;
        islem.InsertArac(plaka, marka, model, aracTipi, yakitTipi, "S", fiyat, motorHacmi,satildiMi);
        
        tbMarka.setText("");
        tbModel.setText("");
        tbAracTipi.setText("");
        tbAracFiyati.setText("");
        tbYakitTipi.setText("");
        tbPlaka.setText("");
        tbMotorHacmi.setText("");
        
        
       
    }//GEN-LAST:event_btnAracSatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       IslemEkrani ekran = new IslemEkrani();
       this.setVisible(false);
       ekran.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatmaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAracSat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAgirlik;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblPlaka;
    private javax.swing.JLabel lblPlaka1;
    private javax.swing.JLabel lblSaat1;
    private javax.swing.JTextField tbAracFiyati;
    private javax.swing.JTextField tbAracTipi;
    private javax.swing.JTextField tbMarka;
    private javax.swing.JTextField tbModel;
    private javax.swing.JTextField tbMotorHacmi;
    private javax.swing.JTextField tbPlaka;
    private javax.swing.JTextField tbYakitTipi;
    // End of variables declaration//GEN-END:variables
}
